### ISSUE TITLE
[BUG] Last Edited By not updating

### ISSUE THREAD

**Issue by champsupertramp** [mariosimao/notion-sdk-php#165]
**Describe the bug**
When trying to update the "Last edited by" property, it doesn't get updated with the following code snippet:

```
 $user = $notion->users()->find("639e3bb1-testestestset");
 $changeEditorPeople = \Notion\Pages\Properties\People::create($user);
 $page = $page->addProperty("Last edited by", $changeEditorPeople);
 ```

**Comment by mariosimao** [comment]
Welcome back, @champsupertramp!

Unfortunately, [Notion API does not allow updating the `Last edited by` property](https://developers.notion.com/reference/page-property-values#last-edited-by).

The same rule is applied for the `Last edited time` property. They are automatically updated with the user who made the changes.

Also, you may be using the wrong property type. `Last edited by` is a property by itself: `Notion\Pages\Properties\LastEditedBy`. Be aware that this will not solve your issue, due to the API rules mentioned above.
