### ISSUE TITLE
[FEATURE] Include the property name / title in the metadata?

### ISSUE THREAD

**Issue by Pr4w** [mariosimao/notion-sdk-php#372]
Hi,

I'm facing an issue where I'm looking for page properties using their ID. However when I obtain that property, I can't access it's name or title.

Would it be possible to include the property's name in the metadata?

Typical use case:
- Get a property by it's ID
- Use that property as a Query Filter

Currently this won't work since you can only add a filter by property name, not by ID.

The only alternative is looping through all the properties manually and creating an array which includes the property metadata and property name.

**Comment by mariosimao** [comment]
Hello @Pr4w. I'm sorry for not getting back to you sooner.

Unfortunately, this is not possible because the Notion API does not return the property name on the [retrieve a page property endpoint](https://developers.notion.com/reference/retrieve-a-page-property).

Looping the page properties is currently the only way.
